- name: Install docker
  hosts: demo-host
  tasks:
  - name: Force update
    apt:
      update_cache: yes

  - name: Install requirements
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker offical GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add fingerprint
    command: apt-key fingerprint 0EBFCD88

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Force update
    apt:
      update_cache: yes

  - name: Install docker
    apt:
      name: docker-ce

